"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const subscriptionController = require("../controllers/subscriptionController");
const auth = require("../middleware/auth");
const router = express.Router();
router.get('/plans', subscriptionController.getSubscriptionPlans);
router.get('/status', subscriptionController.getSubscriptionStatus);
router.post('/', auth.authenticate, subscriptionController.createSubscription);
router.get('/', auth.authenticate, subscriptionController.getSubscription);
router.put('/', auth.authenticate, subscriptionController.updateSubscription);
router.delete('/', auth.authenticate, subscriptionController.cancelSubscription);
exports.default = router;
